### ISSUE TITLE
Not working importing srt files

### ISSUE THREAD

**Issue by nowjordanhappy** [dvkch/Subbie#1]
Hi, great work! I've been looking for something similar and this is really great. Thanks for taking the time of working on this.

I have an issue importing srt files, I think it could be related to the identifier for Imported Type Identifiers on the info.plist.
Because after debugging I got the the typeName as **me.syan.subtitle** and after updating the identifier to **public.srt** it worked.

<img width="579" alt="imagen" src="https://github.com/dvkch/Subtitler/assets/26355419/766aa170-3bab-4714-9aa4-2b1f89a69a83">

I have experience with Swift and iOS but not so much with MacOS development.

**Comment by dvkch** [comment]
Hi,

I'm not sure I follow your problem. The app is registered to open subtitle files as well as text files. You can either use the "File > Open" menu in Subtitler, or right click on a srt or text file in Finder and choose "Open with > Subtitler". Are those options unavailable for you ?

<img width="810" alt="Screenshot 2024-04-12 at 23 37 19" src="https://github.com/dvkch/Subtitler/assets/1838148/4bc0fe06-ee95-4fa8-a41c-421a179cf741">
<img width="726" alt="Screenshot 2024-04-12 at 23 37 33" src="https://github.com/dvkch/Subtitler/assets/1838148/d04c2234-2ab9-4244-90a1-18264298caf0">

**Comment by nowjordanhappy** [comment]
Yes, thanks for answering. Weird, I try doing that and still the same issue.

<img width="258" alt="imagen" src="https://github.com/dvkch/Subtitler/assets/26355419/ed754c47-79a7-4cee-ad8f-8206d54b595b">

https://github.com/dvkch/Subtitler/assets/26355419/f9ed2311-4de9-4d32-81ff-51f5a9f45949

After debugging, somehow the srt file gets a different type name. Maybe it's related to another configuration. 
<img width="681" alt="Screenshot 2024-04-12 at 17 08 38" src="https://github.com/dvkch/Subtitler/assets/26355419/85928e60-434b-4f8f-a14e-e0d4b30298ed">

<img width="739" alt="imagen" src="https://github.com/dvkch/Subtitler/assets/26355419/db23ffdd-f4ab-4565-b380-3520bb193710">

**Comment by nowjordanhappy** [comment]
Using "Open with" option.



https://github.com/dvkch/Subtitler/assets/26355419/63359358-fc0b-4ff4-a25d-ee74daa57c54

**Comment by dvkch** [comment]
Sorry for the long time to answer, I have finally taken some time to look into it, I think the difference between my system ans yours is that I have other apps that can open SRT files, so the file type registers differently. While I investigate further I have updated the switch statements in the read and write methods to include the ID the app declares, do you mind checking if that fixes it for you ?

I am also going to look at how other apps declare their support for SRT files, I might have been wrong in assigning a different type there, I am not extremely versatile in those kinds of macOS app specifics :D 

[Subtitler.zip 1.0.5](https://github.com/dvkch/Subtitler/files/15308038/Subtitler.zip)

**Comment by dvkch** [comment]
After looking more into it, the imported file type makes more sense to me. It is supposed to explain to the system how to handle file types it may not know, recognize them from their extensions and associate a corresponding filetype. Since you don't have another application doing that job for SRT files, Subtitler declares its support for SRT and informs the system it shall be known as `me.syan.subtitle` file from now on...

I have updated the Info.plist to now declare it properly, reverted the changes from 1.0.5 above, here is 1.0.6 to try :) If it works I'll publish it as an official release.

[Subtitler.zip 1.0.6](https://github.com/dvkch/Subtitler/files/15308275/Subtitler.zip)

**Comment by nowjordanhappy** [comment]
Hi, thank you so much for your help and answer. This works perfectly fine. I tested on 2 macs with "Open with" and "Open".
Thanks!

**Comment by dvkch** [comment]
Splendid! Thank you for your insights in this issue, it definitely helped figuring it out!
And since it got me into working for this project again, you'll find a new 1.1.0 release with some notable changes, and I've just submitted the app to the AppStore, should be available [here](https://apps.apple.com/us/app/subbie-subtitle-sync/id6502642752) in a bit
